services:
  - type: web
    name: real-money-magic-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: MONGODB_URL
        value: your-mongodb-url
      - key: JWT_SECRET_KEY
        value: your-secret
