name: Promote Dev to Main

on:
  # Trigger on pushes to develop branch
  push:
    branches:
      - develop
  
  # Manual trigger option
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type YES to confirm promotion'
        required: true
        default: 'NO'

jobs:
  # First job: Create a PR from develop to main
  create-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.confirmation == 'YES' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Create a pull request
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: promote-develop-to-main-${{ github.run_number }}
          base: main
          title: 'Promote Develop to Main'
          body: |
            ## Automated PR to promote Develop to Main
            
            This PR was automatically created by the GitHub Actions workflow.
            
            Workflow run: [Link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
      
      # Output the PR URL to the workflow summary
      - name: Output PR details
        if: steps.create-pr.outputs.pull-request-url != ''
        run: |
          echo "🚀 Pull Request created: ${{ steps.create-pr.outputs.pull-request-url }}"
          echo "Pull Request URL: ${{ steps.create-pr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
